// <auto-generated />
using System;
using FlightTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FlightTrackerDbContext))]
    partial class FlightTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightTracker.Core.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TrackedFlightId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_NotificationRecipients_Email");

                    b.HasIndex("TrackedFlightId")
                        .HasDatabaseName("IX_NotificationRecipients_TrackedFlightId");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlertTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PercentageChange")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrackedFlightId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_PriceAlerts_IsProcessed")
                        .HasFilter("\"IsProcessed\" = false");

                    b.HasIndex("TrackedFlightId")
                        .HasDatabaseName("IX_PriceAlerts_TrackedFlightId");

                    b.ToTable("PriceAlerts");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("PollTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TrackedFlightId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PollTimestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_PriceHistory_PollTimestamp");

                    b.HasIndex("TrackedFlightId")
                        .HasDatabaseName("IX_PriceHistory_TrackedFlightId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TrackedFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalAirportIATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartureAirportIATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NotificationThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("PollingIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TrackedFlights_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TrackedFlights_UserId");

                    b.ToTable("TrackedFlights");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("FlightTracker.Core.Entities.TrackedFlight", "TrackedFlight")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("TrackedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedFlight");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceAlert", b =>
                {
                    b.HasOne("FlightTracker.Core.Entities.TrackedFlight", "TrackedFlight")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("TrackedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedFlight");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.PriceHistory", b =>
                {
                    b.HasOne("FlightTracker.Core.Entities.TrackedFlight", "TrackedFlight")
                        .WithMany("PriceHistories")
                        .HasForeignKey("TrackedFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedFlight");
                });

            modelBuilder.Entity("FlightTracker.Core.Entities.TrackedFlight", b =>
                {
                    b.Navigation("NotificationRecipients");

                    b.Navigation("PriceAlerts");

                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
